name: FloosBackpacks
version: ${project.version}
main: uk.co.tmdavies.floosbackpacks.FloosBackpacks
api-version: 1.12
authors: [Carbonate]
depend: [NBTAPI]
description: Private BackPack Plugin for FloosKingdom
website: www.tmdavies.co.uk
commands:
  backpack:
    aliases: [bp, fbp, floosbackpack, floosbackpacks, fbackpack, fbackpacks, floosbp]
permissions:
  floosbackpacks.give:
    default: op
  floosbackpacks.check:
    default: op
  floosbackpacks.admin:
    children:
      - floosbackpacks.give
      - floosbackpacks.check
    default: op
